[project]
name = "brainstemx-full"
version = "0.1.1"
description = "Anomaly detection within the human brainstem - a research project"
readme = "README.md"
requires-python = "==3.12.8" 
dependencies = [
    "antspyx>=0.5.4",
    "astroid==3.3.10",
    "attrs==25.3.0",
    "blinker==1.9.0",
    "cachetools==6.2.1",
    "certifi==2025.8.3",
    "charset-normalizer==3.4.4",
    "click==8.3.0",
    "colorama==0.4.6 ; sys_platform == 'win32'",
    "contourpy==1.3.2",
    "cycler==0.12.1",
    "dill==0.4.0",
    "fonttools==4.58.5",
    "gitdb==4.0.12",
    "gitpython==3.1.45",
    "idna==3.10",
    "isort==7.0.0",
    "jinja2==3.1.6",
    "joblib==1.5.2",
    "jsonschema==4.25.1",
    "jsonschema-specifications==2025.4.1",
    "kiwisolver==1.4.8",
    "markupsafe==3.0.3",
    "matplotlib==3.10.7",
    "mccabe==0.7.0",
    "narwhals==2.9.0",
    "neuroimagingtools==1.1.4",
    "nibabel==5.3.2",
    "numpy==2.3.4",
    "packaging==25.0",
    "pandas==2.2.3",
    "pathlib==1.0.1",
    "patsy==1.0.2",
    "pillow==12.0.0",
    "platformdirs==4.3.8",
    "plotly==6.3.0",
    "protobuf==6.33.1",
    "pyarrow==22.0.0",
    "pydicom==3.0.1",
    "pylint==4.0.2",
    "pyparsing==3.2.3",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "pyyaml==6.0.3",
    "referencing==0.36.2",
    "requests==2.32.5",
    "rpds-py==0.28.0",
    "scikit-image>=0.25.2",
    "scikit-learn==1.6.1",
    "scipy==1.16.2",
    "six==1.17.0",
    "smmap==5.0.2",
    "statsmodels==0.14.4",
    "suitpy==2.0.0",
    "tenacity==9.1.2",
    "threadpoolctl==3.6.0",
    "toml==0.10.2",
    "tomlkit==0.13.2",
    "tornado==6.5.2",
    "typing-extensions==4.15.0",
    "tzdata==2025.2",
    "urllib3==2.5.0",
    "watchdog==6.0.0 ; sys_platform != 'darwin'",
    "webcolors==25.10.0",
    "seaborn",
]
